Controllers/AddressesController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TrashCollector.Models;

namespace TrashCollector.Controllers
{
    public class AddressesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Addresses
        public ActionResult Index()
        {
            var loggedIn = User.Identity.GetUserId();
            Customer customer = db.Customers.Where(c => c.ApplicationId == loggedIn).FirstOrDefault();
            
            List<Address> addresses = new List<Address>();
            foreach (Address addressList in db.Addresses)
            {
                if (addressList.CustomerId == customer.CustomerId)
                {
                    addresses.Add(addressList);
                }
            }
            return View(addresses);     
        }
        //Get: Addresses/Balance
        public ActionResult Balance ()
        {
            var loggedIn = User.Identity.GetUserId();
            Customer customer = db.Customers.Where(c => c.ApplicationId == loggedIn).FirstOrDefault();
                        
            return View(customer);
        }

        //POST: Address/Balance
        [HttpPost, ActionName("Balance")]
        [ValidateAntiForgeryToken]
        public ActionResult Balance( Customer customer)
        {
           
            return View(customer);
        }
    
        // GET: Addresses/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Address address = db.Addresses.Find(id);
            if (address == null)
            {
                return HttpNotFound();
            }
            return View(address);
        }

        // GET: Addresses/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Addresses/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "AddressId,StreetAddress,City,CityId,State,ZipCode,pickUpDay,vacationStart,vacationEnd")] Address address)
        {
            if (ModelState.IsValid)
            {
                var loggedIn = User.Identity.GetUserId();
                db.Addresses.Add(address);                
                Customer customer = db.Customers.Where(c => c.ApplicationId == loggedIn).FirstOrDefault();
                address.CustomerId = customer.CustomerId;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(address);
        }

        // GET: Addresses/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Address address = db.Addresses.Find(id);
            if (address == null)
            {
                return HttpNotFound();
            }
            return View(address);
        }

        // POST: Addresses/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "AddressId,StreetAddress,City,State,ZipCode,pickUpDay,vacationStart,vacationEnd,SingleDate,CustomerId")] Address address)
        {
            if (ModelState.IsValid)
            {
                db.Entry(address).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(address);
        }

        // GET: Addresses/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Address address = db.Addresses.Find(id);
            if (address == null)
            {
                return HttpNotFound();
            }
            return View(address);
        }

        // POST: Addresses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Address address = db.Addresses.Find(id);
            db.Addresses.Remove(address);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Trash Collector</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <div class="container">
            <div class="navbar-brand">
                @Html.ActionLink("Trash Collector", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>


            <div class="collapse navbar-collapse" id="navbarColor01">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">@Html.ActionLink("Home", "Index", "Home", null, htmlAttributes: new { @class = "nav-link" })</li>
                    <li class="nav-item">@Html.ActionLink("About", "About", "Home", htmlAttributes: new { @class = "nav-link" })</li>
                    <li class="nav-item">@Html.ActionLink("Contact", "Contact", "Home", htmlAttributes: new { @class = "nav-link" })</li>
                    @if (User.IsInRole("Customer"))
                    {
                        <li class="nav-item">@Html.ActionLink("My Addresses", "Index", "Addresses", null, htmlAttributes: new { @class = "nav-link" })</li>
                        <li class="nav-item">@Html.ActionLink("My Balance", "Balance", "Addresses", null, htmlAttributes: new { @class = "nav-link" })</li>
                    }
                    @if (User.IsInRole("Employee"))
                    {
                        <li class="nav-item">@Html.ActionLink("My pickups today", "Index", "Employees",null, htmlAttributes: new { @class = "nav-link" })</li>
                        <li class="nav-item">@Html.ActionLink("All pickups", "AllPU", "Employees", null, htmlAttributes: new { @class = "nav-link" })</li>
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </nav>



    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - FirgensCorp Trash Collector</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>